# Generated by Django 6.0.2 on 2026-02-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP 주소")),
                (
                    "requested_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="요청 시간"),
                ),
            ],
            options={
                "verbose_name": "요청 기록",
                "verbose_name_plural": "요청 기록",
                "indexes": [
                    models.Index(
                        fields=["ip_address", "requested_at"],
                        name="evaluator_r_ip_addr_8a1980_idx",
                    )
                ],
            },
        ),
    ]
