# Generated by Django 6.0.2 on 2026-02-18 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evaluator", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=50)),
                ("provider_id", models.CharField(max_length=200)),
                ("nickname", models.CharField(blank=True, max_length=100)),
                ("profile_image_url", models.URLField(blank=True)),
                ("connected_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "소셜 프로필",
                "verbose_name_plural": "소셜 프로필",
            },
        ),
        migrations.AddField(
            model_name="requestlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="request_logs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="사용자",
            ),
        ),
        migrations.AddIndex(
            model_name="requestlog",
            index=models.Index(
                fields=["user", "requested_at"], name="evaluator_r_user_id_0e0a95_idx"
            ),
        ),
        migrations.AddField(
            model_name="socialprofile",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="social_profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="socialprofile",
            index=models.Index(
                fields=["provider", "provider_id"],
                name="evaluator_s_provide_eaa719_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="socialprofile",
            unique_together={("provider", "provider_id")},
        ),
    ]
