# Generated by Django 6.0.2 on 2026-02-18 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evaluator", "0002_socialprofile_requestlog_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalysisHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP 주소")),
                ("provider", models.CharField(max_length=50, verbose_name="AI 모델")),
                (
                    "resume_filename",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="이력서 파일명"
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="요청 일시"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analysis_histories",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "분석 이력",
                "verbose_name_plural": "분석 이력",
                "ordering": ["-requested_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "requested_at"],
                        name="evaluator_a_user_id_588c28_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "requested_at"],
                        name="evaluator_a_ip_addr_0c60e0_idx",
                    ),
                ],
            },
        ),
    ]
